### PR TITLE
Alt test merge

### PR DESCRIPTION
**Pull request by coleweusthem**
Merged the alt text with the main branch

### CODE REVIEW

**Comment by nfee006** [comment]
Is this just on my side? 

image

**Comment by coleweusthem** [comment]
@nfee006, sorry I've only been pushing files I make changes to, and forgot to push that one, should be fixed now if you pull

**Comment by nfee006** [comment]
Loads now, thanks. The title still isn't translating correctly.

image

I'll look around to see if I can find any other issues.

**Review by nfee006 — CHANGES_REQUESTED** [review]
1. Date selector aria-label and placeholder still need to be translated.
 
image

2. Have you checked everything with the W3 validator? It seems to be throwing some errors. For example, in the header:

image

3. The map alt-text and pagination look great. We'll need to work together to apply this to the rest of the graphs for SCISAT + Alouette. FYI @dreneuw

**Comment by nfee006** [comment]
Looped @dreneuw in for 3. We'll come up with a plan of attack so that we're not duplicating work.

**Comment by dreneuw** [comment]
Great work! Seems like the plan from here would be for me to create a new branch, where I'd make very slight modifications to the detail_table function so that the title of the Summary is a parameter of the function, then I would simply use that function for the 2 other graphs, and generate the data for the table within the graphing functions, just like it is done for the one we've already done.

**Comment by coleweusthem** [comment]
@nfee006 @dreneuw, sounds good to me

**Comment by nfee006** [comment]
@coleweusthem Aria labels for the slider should be translated as well. 

image

We could go with Altitude minimale/Minimum altitude and Altitude maximale/Maximum altitude. If this is set in dash_core_components and needs to be more general we could do Valeur minimal/Minimum value and Valeur maximale/Maximum value

**Comment by nfee006** [comment]
I see you pushed some changes to the slider aria-labels but they still appear as they were on my side (my branch is up to date). Have they changed on your side? 

image

**Comment by coleweusthem** [comment]
@nfee006, you'll need to rebuild dash-core-components or I can send you the new one if you haven't been able to do that yet

**Comment by nfee006** [comment]
I'll need a new one please

**Comment by coleweusthem** [comment]
[dash_core_components.tar.gz](https://github.com/asc-csa/Scisat-App/files/6358483/dash_core_components.tar.gz)

**Comment by nfee006** [comment]
They're in the wrong order unfortunately. Min should be on the left, max on the right. 
image

**Comment by nfee006** [comment]
Once that's fixed we're good to go for these fixes.

**Review by nfee006 — APPROVED** [review]

**Comment by coleweusthem** [comment]
@nfee006, I've added those fixes to a new branch #108

**Pull request merged**
