### PR TITLE
implemented analytics code

### PR DESCRIPTION
**Pull request by coleweusthem**
finished analytics code

### CODE REVIEW

**Comment by coleweusthem** [comment]
this is for #63

**Comment by nfee006** [comment]
Presumably we'll need to add this to the .gitignore?

**Comment by nfee006** [comment]
Sorry, I wasn't clear: I mean to ensure that it won't get pushed to github with the analytics code in it (same issue as with CKAN).

**Comment by coleweusthem** [comment]
@nfee006 if you plan on using analytics in while developing then we probably should. I'll need to go back to this if thats the case and make sure the application still works if it can't find that file.

**Comment by nfee006** [comment]
Roger that. I don't see us adding analytics much before publishing but we'll need to keep that in mind. Even once we publish we'll probably tinker it with it here and there.

**Review by nfee006 — APPROVED** [review]
Approved for #63, assuming this is set up so that the analytics code don't accidentally push to GitHub.

**Pull request merged**
