### PR TITLE
Comms 7

### PR DESCRIPTION
**Pull request by coleweusthem**
partial fix for #38, fixed font issues

### CODE REVIEW

**Comment by nfee006** [comment]
@coleweusthem - is it just me or are these issues new (duplicate text and one center-aligned label)?
image

**Comment by coleweusthem** [comment]
@nfee006, apologies, I must have missed that. I'll take a look and correct them.

**Comment by coleweusthem** [comment]
@nfee006, this should be resolved now

**Review by nfee006 — APPROVED** [review]
The additional issues that I flagged have been corrected, thanks. I am unable to replicate the font error so it must be fixed, approved.

**Pull request merged**
