### PR TITLE
New header/footer

### PR DESCRIPTION
**Pull request by coleweusthem**
replace header/footer with the one from the homepage of canada.ca

### CODE REVIEW

**Review by nfee006 — CHANGES_REQUESTED** [review]
Looks good overall. A couple things: 

1. A line in the breadcrumb isn't translated in french. It should be `<h2>Vous êtes ici :</h2>`image
2. In order to remain consistent with the CSA site, the search bar placeholders should be placeholder="Rechercher dans l'Agence spatiale canadienne" and placeholder="Search Canadian Space Agency"

**Comment by coleweusthem** [comment]
I can fix the first one. for the second one I took the header from canada.ca, the search bar searches canada.ca not the CSA

**Comment by nfee006** [comment]
Ok! In that case, the French version should read placeholder="Rechercher dans Canada.ca" instead of what is there now.

**Comment by coleweusthem** [comment]
the #104 pull should have fixes for this now. Also I'm not sure you changed the config file for the french app to french. I can't thing of another reason you have English in your french version. You may also need to change `APP_PREFIX = '/scisat/'` to whatever url it's on, or it might be pulling all the data and translations from the english instance

**Comment by nfee006** [comment]
Approved based on #104 - with the understanding that the page must also pass the W3 validator

image

**Review by nfee006 — APPROVED** [review]

**Pull request merged**
