### PR TITLE
Direct implementation of Callback

### PR DESCRIPTION
**Pull request by dreneuw**
This fix was done in #116  the branch was based off the Sidebar Layout, which we are not ready to merge yet. This branch is meant to implement the callback fix directly into development.

### CODE REVIEW

**Comment by dreneuw** [comment]
This is complete and should be ready to be merged into development.

**Comment by nfee006** [comment]
FYI @coleweusthem 
I'm going to check this in the morning.

**Comment by nfee006** [comment]
@dreneuw Can you confirm that this works on your side? It's blank on my side and my data files haven't moved. 

Still working with CO so it loads on O3, I select CO and then click update. 

image

**Comment by dreneuw** [comment]
Found the issue and fixed it with the previous commit. Let me know if there are any remaining issues

**Review by nfee006 — APPROVED** [review]
Approved for https://github.com/asc-csa/Scisat-App/issues/116, https://github.com/asc-csa/Scisat-App/issues/85, and https://github.com/asc-csa/Scisat-App/issues/90.

**Pull request merged**
