### PR TITLE
Implementation of Alt text

### PR DESCRIPTION
**Pull request by dreneuw**
Implementation of the alternative text tables for the remaining 2 graphs

### CODE REVIEW

**Comment by nfee006** [comment]
Great! Any objections @colewusthem? Does this meet web standards?

**Comment by dreneuw** [comment]
@coleweusthem Yes, it is because I havent implemented the time series data yet, I am currently working on that

**Comment by dreneuw** [comment]
@coleweusthem all 3 tables should be functional with the most recent commit. I will need to add translation for column headers and everything should be in place. It is important to note that this branch was created from development and so does not incorporate the changes done in #108

**Comment by coleweusthem** [comment]
@dreneuw, I just merged my branch into yours

**Comment by nfee006** [comment]
Checking it now.

**Comment by nfee006** [comment]
Wow, great work everyone! A few minor things. 

1. Make sure that capitalization is consistent in the headers please (first word cap, no need after that). The time series one is ok in that regard.
image

2. Table titles aren't translating. 
image

3. World graph of mean gas concentrations -> I'd call it a map. 
4. Mean concentration distribution on altitude -> Mean gas concentration as a function of altitude? Too technical?
5.  Time series -> Gas concentration over time or something like that

**Comment by nfee006** [comment]
@coleweusthem what does "header fixes" actually address?

**Comment by coleweusthem** [comment]
@nfee006, I had missed the navigation options that were required when you hit tab after page load

**Comment by nfee006** [comment]
Is that associated with a comms issue or just general implementation?

**Comment by coleweusthem** [comment]
@nfee006 #58

**Comment by nfee006** [comment]
Approved for https://github.com/asc-csa/Scisat-App/issues/57
@dreneuw just fixed a bug that made it so that updates to the graphs were not reflected in the alt-text (ie. change the altitude and all values still appear in the alt-text tables). In doing so, it seems that the blank table pages returned. 
image
Any thoughts @coleweusthem? I'm going to log this as its own issue.

**Review by nfee006 — APPROVED** [review]

**Pull request merged**
