### PR TITLE
Comms 1

### PR DESCRIPTION
**Pull request by coleweusthem**
should address #32 as well and changing the default gas back to Ozone

### CODE REVIEW

**Review by nfee006 — CHANGES_REQUESTED** [review]
One typo remains
image

Larger issues: 

1. When I click on "Update", it now opens a new webpage. 
2. It's back to showing "Ozone" as the default gas but it's still actually displaying the CO data under the O3 name. I don't even have O3 on my VM and it's displaying it (+ the graphs are wrong for that data). Not sure why that's happening but will investigate. 

image

**Comment by coleweusthem** [comment]
@nfee006, strange investigating

**Comment by coleweusthem** [comment]
I've fixed the first 2, but I'm not sure whats happening with the wrong data, I don't have CO data at all in my data folder and it gives me this error when I try to load it
Screen Shot 2021-03-29 at 11 53 52 AM

I also get the ozone data by default:

Screen Shot 2021-03-29 at 11 56 29 AM

**Comment by nfee006** [comment]
Roger that, I'll investigate more on my side after this meeting.

**Comment by nfee006** [comment]
To replicate: 

1. Restart app-launcher
2. Select CO in the gas dropdown menu. 
3. Click update.
4. Refresh the page. 
5.  Dropdown defaults to Ozone. Data displayed is CO.

Do you have the same issue on your side?

**Comment by coleweusthem** [comment]
@nfee006, I don't do you think it's because I changed the data path? I do have it still showing the ozone data when I select carbon monoxide without the file tho, it gives the error that the data is missing an leaves ozone in the graphs if thats what you mean.

**Comment by nfee006** [comment]
Does it stay with the wrong data if you refresh the page? That's the potential issue I see. You might need to have load the CO file to see it.

**Comment by coleweusthem** [comment]
Comms-7 had all these commits to avoid a merge conflict, so it closed this too. and I'll check. I think I deleted the CO data so let me redownload it and see

**Comment by coleweusthem** [comment]
I see that issue, if I reload the page, it defaults to the ozone in the drop down, but displays CO. I'll take a look and see if I can't figure it out. Do you know if it did that before?

**Comment by nfee006** [comment]
I don't remember it doing that. I can't help but think it's a callback/global variable issue. @dreneuw: do you think it could be related to https://github.com/asc-csa/Scisat-App/issues/85 ?

**Comment by dreneuw** [comment]
Yes, this seems like a problem caused from global variables, when switching the gas, it sets the global variable. Reloading from there resets the dropdown, but not the global variable, and loading is done using the global variable. This issue should be fixed with #85 as the new callback system will load whatever is in the dropdown form rather than a backend value.

**Comment by nfee006** [comment]
Ok, that sounds reasonable. Mystery solved for the moment. I'll log this as an issue so that we know to check back once #85 is implemented.

**Pull request merged**
