### PR TITLE
Comms 18

### PR DESCRIPTION
**Pull request by coleweusthem**
should resolve issue #50

### CODE REVIEW

**Comment by coleweusthem** [comment]
@nfee006, sorry for the confusion, I must have forgotten to save the file. You can see the github fix here. #78

**Comment by nfee006** [comment]
@coleweusthem I still only see the analytics.py file in the github link commit

**Comment by coleweusthem** [comment]
@nfee006, yeah, I somehow didn't include it in that commit, but the next one with the aria role. Sorry for the confusion.

**Review by nfee006 — APPROVED** [review]
Approved for #50 and #53

**Pull request merged**
