### PR TITLE
Validator issues

### PR DESCRIPTION
**Pull request by coleweusthem**

### CODE REVIEW

**Comment by coleweusthem** [comment]
[dash_core_components.tar.gz](https://github.com/asc-csa/Scisat-App/files/6393372/dash_core_components.tar.gz)
You will need this

**Comment by coleweusthem** [comment]
@nfee006, that dash-core-component will break alouette until you update it to the branch I'm working on

**Comment by nfee006** [comment]
@coleweusthem 
This just seems like the dcc validator in red? Also, if there are 2 errors in the lat/long/dates then it only appears as 1. 

image.

From GCWeb 
image

https://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html

**Comment by dreneuw** [comment]
@coleweusthem are you currently working on this? If not, I will resolve the conflicts on this branch right now so that we avoid conflicting between my work and your work.

**Comment by coleweusthem** [comment]
@dreneuw, not currently working on it thanks!

**Comment by nfee006** [comment]
Now this is appearing sometimes but just in English. I'm confused.

image

**Comment by coleweusthem** [comment]
@nfee006, lets wait for david to add his fixes, then take another look.

**Comment by nfee006** [comment]
FYI https://github.com/asc-csa/Scisat-App/pull/118

**Review by nfee006 — CHANGES_REQUESTED** [review]
Confirmed that the "this form cannot be submitted" section is not appearing in English or French. 

image
image

**Comment by nfee006** [comment]
@coleweusthem Is this ready for me to check or should I wait?

**Comment by coleweusthem** [comment]
The validator should be ready to look at

**Comment by nfee006** [comment]
@coleweusthem 

What's this? 

image

**Comment by nfee006** [comment]
Fantastic. Approved for the validator once the "Did not load things" text is removed. Now checking for analytics (which I am now realizing is where "Did not load things" came from). 

image

image

**Comment by coleweusthem** [comment]
@nfee006, my bad I must have accidentally pushed my testing text

**Comment by nfee006** [comment]
@coleweusthem it's not super clear on my end where the analytics.py text is actually getting included. I only skimmed your commit but I'm assuming that you overwrote it with your testing "did not load" h2. Is that right?

**Comment by coleweusthem** [comment]
@nfee006, I have an empty string that gets used if there is not analytics file, I had replace it with that message. I'll fix it shortly

**Comment by nfee006** [comment]
The footer test text is gone but there's still a header one

image

**Comment by coleweusthem** [comment]
@nfee006, I'm not seeing it, did you happen to add it to your analytics file?

**Comment by nfee006** [comment]
Facepalm - seems fitting that this is happening at 404pm on a Friday. 

Approved for analytics. Thanks @coleweusthem

**Review by nfee006 — APPROVED** [review]

**Pull request merged**
