### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by coleweusthem**
bug fixes

### CODE REVIEW

**Comment by coleweusthem** [comment]
I had to use javascript to remove the 'aria-owns' I spent a good amount of time trying to track it down, and it seems it can only be changed in another repo, and I don't want to open another repo to maintain.

**Comment by nfee006** [comment]
I'm still seeing these two on my side
image
image

Any ideas?

**Comment by dreneuw** [comment]
Also, just wondering, but it seems like the pages are not limited on the tables. In more details, even when there is no more data, you can go to the next page of the table, at which point nothing is displayed:
This page should be the last page (example):
image
But I can go to the next page, which results in this:
image
I can keep going infinitely.
This seems like it would not be a dealbreaker but it might cause some issues with screen readers

**Comment by coleweusthem** [comment]
> I'm still seeing these two on my side
> image
> image
> 
> Any ideas?

The first one seems to be from the gcweb theme, we need them to give us a proper implementation guide I think.

And the second one I'm not seeing at all when I use the validator.

**Comment by coleweusthem** [comment]
@dreneuw, I don't want to cause merge conflicts with what you are working on, but if you use 'page_count' from the table as an input you can use that to make sure curr_page never goes past that. 

```
If curr_page > page_count:
    curr_page = page_count
```

**Pull request merged**
